-- Keep a log of any SQL queries you execute as you solve the mystery.
SELECT * FROM crime_scene_reports;
SELECT * FROM crime_scene_reports WHERE street = 'Humphrey Street';
SELECT * FROM crime_scene_reports WHERE street = 'Humphrey Street' AND month = 7 AND day = 28;
SELECT * FROM interviews;
SELECT * FROM interviews WHERE year >= 2024 AND month >= 7;
SELECT * FROM interviews WHERE year = 2024 AND month = 7 AND day = 28;
SELECT * FROM bakery_security_logs WHERE year = 2024 AND month = 7 AND day = 28;
SELECT * FROM phone_calls WHERE year = 2024 AND month = 7 AND day = 28 AND duration < 60;
SELECT * FROM atm_transactions WHERE year = 2024 AND month = 7 AND day = 28;
SELECT * FROM atm_transactions WHERE year = 2024 AND month = 7 AND day = 28 AND atm_location = 'Humphrey Lane' AND transaction_type = 'withdraw';
SELECT * FROM flights WHERE year = 2024 AND day = 28 AND month = 7;
SELECT * FROM flights WHERE year = 2024 AND day = 28 AND month = 7 ORDER BY hour, minute DESC;
SELECT city, full_name, abbreviation FROM airports JOIN flights ON origin_airport_id = airports.id WHERE flights.year = 2024 AND flights.day = 28 AND flights.month = 7 ORDER BY flights.hour, flights.minute DESC;
SELECT * FROM flights WHERE year = 2024 AND day = 29 AND month = 7 ORDER BY hour, minute DESC;
SELECT city, full_name, abbreviation FROM airports JOIN flights ON origin_airport_id = airports.id WHERE flights.year = 2024 AND flights.day = 29 AND flights.month = 7 ORDER BY flights.hour, flights.minute DESC;
SELECT * FROM passengers WHERE flight_id = 36;
SELECT people.name FROM people JOIN passengers ON passengers.passport_number = people.passport_number WHERE passengers.flight_id = 36;
SELECT * FROM people JOIN passengers ON passengers.passport_number = people.passport_number WHERE passengers.flight_id = 36;
SELECT * FROM people JOIN passengers ON passengers.passport_number = people.passport_number JOIN phone_calls ON people.phone_number = phone_calls.caller WHERE passengers.flight_id = 36;
SELECT people.name, people.id, people.phone_number, people.passport_number, people.license_plate FROM people JOIN passengers ON passengers.passport_number = people.passport_number JOIN phone_calls ON people.phone_number = phone_calls.caller WHERE passengers.flight_id = 36;
SELECT people.name, people.id, people.phone_number, people.passport_number, phone_calls.caller, phone_calls.duration FROM people JOIN passengers ON passengers.passport_number = people.passport_number JOIN phone_calls ON people.phone_number = phone_calls.caller WHERE passengers.flight_id = 36;
SELECT people.name, people.id, people.phone_number, people.passport_number, phone_calls.caller, phone_calls.duration FROM people JOIN passengers ON passengers.passport_number = people.passport_number JOIN phone_calls ON people.phone_number = phone_calls.caller WHERE passengers.flight_id = 36 AND phone_calls.duration < 60;
SELECT * FROM airports WHERE id = 4;
SELECT people.name, people.id, people.phone_number, people.passport_number, phone_calls.caller, phone_calls.duration, bank_accounts.account_number FROM people JOIN passengers ON passengers.passport_number = people.passport_number JOIN phone_calls ON people.phone_number = phone_calls.caller JOIN bank_accounts ON bank_accounts.person_id = people.id JOIN atm_transactions ON bank_accounts.account_number = atm_transactions.account_number WHERE passengers.flight_id = 36 AND phone_calls.duration < 60;
SELECT * FROM people JOIN passengers ON passengers.passport_number = people.passport_number JOIN phone_calls ON people.phone_number = phone_calls.caller JOIN bank_accounts ON bank_accounts.person_id = people.id JOIN atm_transactions ON bank_accounts.account_number = atm_transactions.account_number WHERE passengers.flight_id = 36 AND phone_calls.duration < 60;
SELECT * FROM people JOIN passengers ON passengers.passport_number = people.passport_number JOIN phone_calls ON people.phone_number = phone_calls.caller JOIN bank_accounts ON bank_accounts.person_id = people.id JOIN atm_transactions ON bank_accounts.account_number = atm_transactions.account_number JOIN bakery_security_logs ON bakery_security_logs.license_plate = people.license_plate WHERE passengers.flight_id = 36 AND phone_calls.duration < 60;
SELECT people.name, bakery_security_logs.activity FROM people JOIN passengers ON passengers.passport_number = people.passport_number JOIN phone_calls ON people.phone_number = phone_calls.caller JOIN bank_accounts ON bank_accounts.person_id = people.id JOIN atm_transactions ON bank_accounts.account_number = atm_transactions.account_number JOIN bakery_security_logs ON bakery_security_logs.license_plate = people.license_plate WHERE passengers.flight_id = 36 AND phone_calls.duration < 60;
SELECT people.name, bakery_security_logs.activity, bakery_security_logs.hour, bakery_security_logs.minute FROM people JOIN passengers ON passengers.passport_number = people.passport_number JOIN phone_calls ON people.phone_number = phone_calls.caller JOIN bank_accounts ON bank_accounts.person_id = people.id JOIN atm_transactions ON bank_accounts.account_number = atm_transactions.account_number JOIN bakery_security_logs ON bakery_security_logs.license_plate = people.license_plate WHERE passengers.flight_id = 36 AND phone_calls.duration < 60;
SELECT people.name, bakery_security_logs.activity, bakery_security_logs.hour, bakery_security_logs.minute FROM people JOIN passengers ON passengers.passport_number = people.passport_number JOIN phone_calls ON people.phone_number = phone_calls.caller JOIN bank_accounts ON bank_accounts.person_id = people.id JOIN atm_transactions ON bank_accounts.account_number = atm_transactions.account_number JOIN bakery_security_logs ON bakery_security_logs.license_plate = people.license_plate WHERE passengers.flight_id = 36 AND phone_calls.duration < 60 ORDER BY bakery_security_logs.hour, bakery_security_logs.minute;
